<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="eParPlusProductLinePartDetail.aspx.cs"
    Inherits="VCTWebApp.Shell.Views.ProductLinePartDetail" Title="ProductLinePartDetail"
    MasterPageFile="~/Site1.master" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxtk" %>
<%@ Register Assembly="CustomControls" Namespace="CustomControls" TagPrefix="cc1" %>
<asp:Content ID="content" ContentPlaceHolderID="DefaultContent" runat="Server">
    <script type="text/javascript">
        // It is important to place this JavaScript code after ScriptManager1
        var xPos, yPos;
        var prm = Sys.WebForms.PageRequestManager.getInstance();

        function SavePnlGridScrollPos() {
            prm.add_beginRequest(BeginRequestHandler);
            prm.add_endRequest(EndRequestHandler);
        }
    </script>
    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
        <ContentTemplate>
            <table align="left" border="0" width="100%">
                <tr>
                    <td align="center">
                        <table class="maintable" border="0" align="center" cellpadding="3" cellspacing="0"
                            width="80%">
                            <tr class="header">
                                <td align="center" colspan="3">
                                    <asp:Label ID="lblHeader" runat="server" Text="Part Setup"></asp:Label>
                                </td>
                            </tr>
                            <tr>
                                <td valign="top" align="left" style="width: 250px">
                                    <table class="leftlistboxborder" cellspacing="0" cellpadding="0">
                                        <tr>
                                            <td>
                                                <asp:Label ID="lblSelectPartType" runat="server" Text="Select Part Type" CssClass="listboxheading"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td valign="top">
                                                <asp:Panel ID="pnlSelectPartType" runat="server" ScrollBars="Auto" Height="500px"
                                                    Width="250px">
                                                    <asp:TreeView ID="tvwSelectPartType" runat="server" AutoGenerateDataBindings="False"
                                                        OnSelectedNodeChanged="tvwSelectPartType_SelectedNodeChanged" ShowLines="True"
                                                        SelectedNodeStyle-BackColor="#696969" SelectedNodeStyle-ForeColor="#FFFFFF">
                                                    </asp:TreeView>
                                                </asp:Panel>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                <td valign="top" align="left">
                                    <table width="100%" cellspacing="0" cellpadding="0" border="0">
                                        <tr>
                                            <td align="left">
                                                <asp:Panel ID="pnlPartDetails" runat="server" Height="510px" CssClass="pnlDetail"
                                                    ScrollBars="Auto" Style="padding: 0 0px 0px;">
                                                    <asp:GridView ID="gdvPartDetails" runat="server" AutoGenerateColumns="false" ShowHeaderWhenEmpty="true"
                                                        Style="height: 100%" OnRowCancelingEdit="gdvPartDetails_RowCancelingEdit" OnRowCommand="gdvPartDetails_RowCommand"
                                                        OnRowEditing="gdvPartDetails_RowEditing" SkinID="GridView">
                                                        <Columns>
                                                            <asp:TemplateField HeaderStyle-Width="18%" ItemStyle-Width="18%" ItemStyle-HorizontalAlign="Center"
                                                                HeaderText="Ref #">
                                                                <ItemTemplate>
                                                                    <asp:HiddenField ID="hndRefNum" runat="server" Value='<%# Eval("RefNum") %>' />
                                                                    <asp:Label ID="lblPartNum" runat="server" Text='<%# Eval("RefNum") %>' />
                                                                </ItemTemplate>
                                                            </asp:TemplateField>
                                                            <asp:TemplateField HeaderStyle-Width="35%" ItemStyle-Width="35%" ItemStyle-HorizontalAlign="Center"
                                                                HeaderText="Part Type">
                                                                <ItemTemplate>
                                                                    <asp:Label ID="lblPartType" runat="server" Text='<%# Eval("PartType") %>' />
                                                                </ItemTemplate>
                                                            </asp:TemplateField>
                                                            <asp:TemplateField HeaderStyle-Width="17%" ItemStyle-Width="17%" ItemStyle-HorizontalAlign="Center"
                                                                HeaderText="Size">
                                                                <ItemTemplate>
                                                                    <asp:Label ID="lblSize" runat="server" Text='<%# Eval("Size") %>' />
                                                                </ItemTemplate>
                                                            </asp:TemplateField>
                                                            <asp:TemplateField HeaderStyle-Width="15%" HeaderText="Default PAR Level" ItemStyle-Width="15%"
                                                                HeaderStyle-HorizontalAlign="Center" ItemStyle-HorizontalAlign="Center">
                                                                <ItemTemplate>
                                                                    <asp:Label ID="lblPARLevelQty" runat="server" Text='<%# Eval("DefaultPARLevel") %>'></asp:Label>
                                                                </ItemTemplate>
                                                                <EditItemTemplate>
                                                                    <asp:TextBox ID="txtPARLevelQty" MaxLength="3" Width="90%" runat="server" Text='<%#Eval("DefaultPARLevel") %>'
                                                                        CssClass="textbox" />
                                                                    <ajaxtk:FilteredTextBoxExtender ID="txtFilteredTextBoxExtender" runat="server" Enabled="True"
                                                                        FilterType="Custom" TargetControlID="txtPARLevelQty" ValidChars="0123456789">
                                                                    </ajaxtk:FilteredTextBoxExtender>
                                                                </EditItemTemplate>
                                                            </asp:TemplateField>
                                                            <asp:TemplateField HeaderStyle-Width="10%" ItemStyle-Width="10%" ItemStyle-HorizontalAlign="Center">
                                                                <ItemTemplate>
                                                                    <asp:LinkButton ID="lnkEdit" CausesValidation="false" CommandName="Edit" runat="server">
                                                                        <asp:Image ID="imgEdit" runat="server" ImageUrl="~/Images/Modify.gif" BorderStyle="None"
                                                                            ToolTip="Edit" AlternateText="Edit" OnClick="javascript:SavePnlGridScrollPos();" /></asp:LinkButton>
                                                                </ItemTemplate>
                                                                <EditItemTemplate>
                                                                    <asp:LinkButton ID="lnkUpdate" CommandName="UpdateRec" runat="server" CausesValidation="false">
                                                                        <asp:Image ID="imgUpdate" runat="server" ImageUrl="~/Images/Update.gif" BorderStyle="None"
                                                                            ToolTip="Update" AlternateText="Update" OnClick="javascript:SavePnlGridScrollPos();" /></asp:LinkButton>
                                                                    <asp:LinkButton ID="lnkCancel" CausesValidation="false" CommandName="Cancel" runat="server">
                                                                        <asp:Image ID="imgCancel" runat="server" ImageUrl="~/Images/Cancel.gif" BorderStyle="None"
                                                                            ToolTip="Cancel" AlternateText="Cancel" OnClick="javascript:SavePnlGridScrollPos();" /></asp:LinkButton>
                                                                </EditItemTemplate>
                                                                <HeaderTemplate>
                                                                    <asp:Label ID="Label4" runat="server" Text="Action" />
                                                                </HeaderTemplate>
                                                            </asp:TemplateField>
                                                        </Columns>
                                                    </asp:GridView>
                                                </asp:Panel>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td align="left" colspan="2">
                                    <asp:Panel ID="pnlButton" CssClass="ActionPanel" runat="server">
                                        <table cellpadding="0" cellspacing="0" width="100%">
                                            <tr style="height: 20px">
                                                <td align="left" width="50%">
                                                    <asp:Label ID="lblError" runat="server" CssClass="ErrorText"></asp:Label>
                                                </td>
                                            </tr>
                                        </table>
                                    </asp:Panel>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </ContentTemplate>
    </asp:UpdatePanel>
    <ajaxtk:ModalPopupExtender ID="modalPopup" runat="server" TargetControlID="UpdatePnlProgress2"
        PopupControlID="UpdatePnlProgress2" BackgroundCssClass="modalPopup" />
</asp:Content>
